language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-18mode
  - jruby-19mode
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/rails_4.1.gemfile
